"""Pure text generation of Fair FP job scripts.

Verified against the compiled fp binary (see agent_docs/model_integration.md):
- READJOB must be given at fp's initial stdin prompt, not inside an INPUT file.
- CHANGEVAR reads '<VAR> <OP>' on one line and the numeric value on the NEXT
  line; the block ends with a lone ';'.
- SOLVE ... FILEWRITE=<file> FILEVAR=KEYBOARD reads the metric list from the
  following lines, terminated by ';'.
"""

from app.domain.entities import FairChange
from app.domain.enums import ChangeType

from app.business.routing import CHANGEVAR_OPS
from app.infrastructure.fair.periods import to_fair_period

BASE_SNAPSHOT_FILE = "BASE.BIN"
BASE_OUTPUT_FILE = "BASEOUT.TXT"
SCENARIO_OUTPUT_FILE = "SCENOUT.TXT"
BASE_JOB_FILE = "BASEJOB.TXT"
SCENARIO_BODY_FILE = "SCENBODY.TXT"

SETYYTOY_MARKER = "SETYYTOY;"


def build_base_job(fminput_text: str, metrics: list[str],
                   solve_start: str, solve_end: str) -> str:
    """Base job: the vendored fminput.txt up to and including SETYYTOY;
    (load + estimate + solve + set YY), then a WRITEJOB snapshot and a
    machine-readable re-solve of the base."""
    idx = fminput_text.find(SETYYTOY_MARKER)
    if idx < 0:
        raise ValueError(f"fminput.txt does not contain {SETYYTOY_MARKER!r}")
    head = fminput_text[: idx + len(SETYYTOY_MARKER)]
    metric_lines = "\n".join(metrics)
    tail = f"""
@
@ Generated by AI Economic Board: snapshot base state, write base metrics
@
WRITEJOB FILE={BASE_SNAPSHOT_FILE};
SMPL {to_fair_period(solve_start)} {to_fair_period(solve_end)};
SOLVE DYNAMIC OUTSIDE NORESET FILEWRITE={BASE_OUTPUT_FILE} FILEVAR=KEYBOARD;
{metric_lines}
;
QUIT;
"""
    return head + tail


def build_scenario_body(change: FairChange, metrics: list[str],
                        solve_start: str, solve_end: str) -> str:
    """Scenario body executed after READJOB restored the base state."""
    op = CHANGEVAR_OPS[change.change_type]
    value = change.value
    if change.change_type is ChangeType.PERCENT:
        # user PERCENT is in percent; Fair's ADDSAMEPCT expects a fraction
        value = value / 100
    lines = [f"SMPL {to_fair_period(solve_start)} {to_fair_period(solve_end)};"]
    if change.requires_exogenous:
        lines.append(f"EXOGENOUS VARIABLE={change.fair_variable};")
    lines += [
        "CHANGEVAR;",
        f"{change.fair_variable} {op}",
        f"{value}",
        ";",
        f"SOLVE DYNAMIC OUTSIDE NORESET FILEWRITE={SCENARIO_OUTPUT_FILE} FILEVAR=KEYBOARD;",
        *metrics,
        ";",
        "QUIT;",
    ]
    return "\n".join(lines) + "\n"


def base_stdin() -> str:
    return f"INPUT FILE={BASE_JOB_FILE} ;\n"


def scenario_stdin() -> str:
    return f"READJOB FILE={BASE_SNAPSHOT_FILE} ;\nINPUT FILE={SCENARIO_BODY_FILE} ;\n"
