"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-10 14:55:44.484456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=32), nullable=False),
    sa.Column('version_label', sa.String(length=128), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'version_label', name='uq_model_versions')
    )
    op.create_table('model_artifacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_version_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baselines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fair_model_version_id', sa.BigInteger(), nullable=False),
    sa.Column('solve_start', sa.String(length=8), nullable=False),
    sa.Column('solve_end', sa.String(length=8), nullable=False),
    sa.Column('snapshot_artifact_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','RETIRED')", name='ck_baselines_status'),
    sa.ForeignKeyConstraint(['fair_model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['snapshot_artifact_id'], ['model_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('baseline_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('baseline_id', sa.BigInteger(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baseline_id', 'metric', 'period', name='uq_baseline_metrics')
    )
    op.create_table('simulation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('baseline_id', sa.BigInteger(), nullable=True),
    sa.Column('horizon_quarters', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','RUNNING','COMPLETED','FAILED')", name='ck_simulation_runs_status'),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('economic_changes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('variable_id', sa.String(length=64), nullable=False),
    sa.Column('model_route', sa.String(length=32), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('change_value', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('llm_interpretations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('stop_reason', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('metric_deltas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('baseline_value', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('changed_value', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('absolute_delta', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('percentage_delta', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'metric', 'period', name='uq_metric_deltas')
    )
    op.create_table('simulation_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'metric', 'period', name='uq_simulation_metrics')
    )
    op.create_table('simulation_model_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'model_version_id', name='uq_sim_model_versions')
    )
    op.create_table('tax_calculator_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('reform', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_iitax', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('reform_iitax', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('base_payrolltax', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('reform_payrolltax', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('base_combined', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('reform_combined', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('base_agi', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('base_expanded_income', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('total_weight', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('soi_iitax', sa.Boolean(), nullable=False),
    sa.Column('taxcalc_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('tax_fair_adapter_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tax_calculator_result_id', sa.BigInteger(), nullable=False),
    sa.Column('mapping_id', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('source_variable_id', sa.String(length=64), nullable=False),
    sa.Column('target_fair_variable', sa.String(length=16), nullable=False),
    sa.Column('fair_change_type', sa.String(length=16), nullable=False),
    sa.Column('derived_delta', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('quarterly_allocation_method', sa.String(length=32), nullable=False),
    sa.Column('quarterly_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conversion_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.ForeignKeyConstraint(['tax_calculator_result_id'], ['tax_calculator_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_fair_adapter_results')
    op.drop_table('tax_calculator_results')
    op.drop_table('simulation_model_versions')
    op.drop_table('simulation_metrics')
    op.drop_table('metric_deltas')
    op.drop_table('llm_interpretations')
    op.drop_table('economic_changes')
    op.drop_table('simulation_runs')
    op.drop_table('baseline_metrics')
    op.drop_table('baselines')
    op.drop_table('model_artifacts')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
